name: CI/CD - Frontend

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Bump version using GitHub run number (simple versioning)
    - name: Set image version
      id: vars
      run: |
        VERSION="v1.0.${{ github.run_number }}"
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t ivosalumbides/simple-notes-app-frontend:${{ env.VERSION }} .
        docker tag ivosalumbides/simple-notes-app-frontend:${{ env.VERSION }} ivosalumbides/simple-notes-app-frontend:latest

    #### PUSH TO DOCKER HUB ####

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to DockerHub
      run: |
        docker push ivosalumbides/simple-notes-app-frontend:${{ env.VERSION }}
        docker push ivosalumbides/simple-notes-app-frontend:latest

    #### PUSH TO GITHUB OCI ####

    - name: Login to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GH_PAT }}

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker tag ivosalumbides/simple-notes-app-frontend:${{ env.VERSION }} ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-notes-app-frontend:${{ env.VERSION }}
        docker tag ivosalumbides/simple-notes-app-frontend:${{ env.VERSION }} ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-notes-app-frontend:latest

        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-notes-app-frontend:${{ env.VERSION }}
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-notes-app-frontend:latest
